%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: ML_dataset_raw.xlsx
%    Worksheet: Bottle_X, Bottle_Y, Gripper
%
% Auto-generated by MATLAB on 19-Jun-2020 10:24:12

%% Setup the Import Options and import the data
file_loc = "C:\Users\godpo\Documents\GitHub\Machine-Learning-Tilt-Sensing\ML_dataset_raw.xlsx";

opts = spreadsheetImportOptions("NumVariables", 16);
opts_array = {opts opts opts opts opts};

% Specify sheet and range
opts_array{1}.Sheet = "Bottle_X";
opts_array{2}.Sheet = "Bottle_Y";
opts_array{3}.Sheet = "Gripper";
opts_array{1}.DataRange = "A2:P1559";
opts_array{2}.DataRange = "A2:P2039";
opts_array{3}.DataRange = "A2:P1591";

for i = 1:3
    % Specify column names and types
    opts_array{i}.VariableNames = ["Time", "SensorA_1", "SensorA_2", "SensorA_3", "SensorA_4",...
        "SensorB_1", "SensorB_2", "SensorB_3", "SensorB_4", "SensorB_5",...
        "IMU_1", "IMU_2", "X_Axis", "Y_Axis", "X_Errordeg", "Y_Errordeg"];
    opts_array{i}.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
end

% Specify variable properties
% opts = setvaropts(opts, ["VarName17", "VarName18"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["VarName17", "VarName18"], "EmptyFieldRule", "auto");

% Import the data
trainDataX = readtable(file_loc, opts_array{1}, "UseExcel", false);
trainDataY = readtable(file_loc, opts_array{2}, "UseExcel", false);
testData = readtable(file_loc, opts_array{3}, "UseExcel", false);


%% Clear Temporary Variables:
vars = {'opts','file_loc','i','opts_array'};
clear(vars{:});
clear vars;
